---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: magnognaniri
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-sway-atomic
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      copr:
        - avengemedia/dms
        - avengemedia/danklinux
    install:
      packages:  
      #niri
        - niri
        - dms
        - niri-settings
        - dms-greeter
        - material-symbols-fonts
        - danksearch
        - cava
        - cliphist
        - wl-clipboard
        - dgop
        - dsearch
        - matugen
        - qt6-multimedia
        
  - type: dnf
    install:
      packages:  
      #niri
        - niri
        - niri-settings
      #utils
        - micro
        - lshw
        - fish
        - cockpit
        - cockpit-podman
      #build
        - make
        - gawk
      #appimages
        - fuse
        - fuse-libs
        
#    remove:
#      packages:
#        - firefox
#        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen 
          - page.codeberg.libre_menu_editor.LibreMenuEditor 
          - org.onlyoffice.desktopeditors
          - com.mattjakeman.ExtensionManager
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal

  - type: systemd
    system:
      enabled:
      - cockpit.socket

  ## - type: script
  ##  snippets:
  ##    - "gsettings set org.gnome.desktop.interface gtk-enable-primary-paste true" #enable middleclick paste
  ##  scripts:
  ##   - ble.sh
  
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
